nodeLinker: pnp

packageExtensions:
  "@aws-sdk/config-resolver@*":
    peerDependencies:
      "@aws-sdk/node-config-provider": "*"
  "@aws-sdk/middleware-bucket-endpoint@*":
    peerDependencies:
      "@aws-sdk/node-config-provider": "*"
  "@aws-sdk/middleware-retry@*":
    peerDependencies:
      "@aws-sdk/node-config-provider": "*"
  "@aws-sdk/types@*":
    dependencies:
      tslib: "*"
  "@aws-sdk/util-retry@*":
    dependencies:
      "@aws-sdk/types": "*"
  "@smithy/config-resolver@*":
    dependencies:
      "@smithy/node-config-provider": "*"
  "@smithy/middleware-retry@*":
    dependencies:
      "@smithy/node-config-provider": "*"
  "@smithy/util-retry@*":
    dependencies:
      "@smithy/types": "*"
  aws-cdk-local@*:
    dependencies:
      aws-cdk: "*"
  debug@*:
    dependencies:
      supports-color: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"
